branches:
  only:
    - master
#    - next
  
language: erlang
otp_release:
   - 17.1
   - R16B03-1

before_install:
  - "sudo apt-get update && sudo apt-get install build-essential libssl-dev libexpat1-dev libaprutil1-dev libavahi-compat-libdnssd-dev"
  - "./configure"

notifications:
  email:
    recipients:
      - erocci-dev@ow2.org
    on_success: change
    on_failure: always
